name: festi
description: A new Flutter application.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  qr_code_scanner: ^0.3.0
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  provider:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  flutter_native_splash: ^0.1.4

flutter_native_splash:
  image: assets/images/splash.png
  color: 42a5f5

flutter_icons:
  image_path: 'assets/images/logo_splash.png'
  android: true
  ios: true

flutter:
  fonts:
    - family: ClearSans
      fonts:
        - asset: assets/fonts/clearsansbold.ttf
    - family: OpenSans-ExtraBold
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

  uses-material-design: true

  assets:
    - assets/images/

